# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170622_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='relations',
        ),
    ]
