# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170616_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='post.Comment'),
        ),
    ]
